Repository Pirate-Weather/pirate-weather-code, pull requests merged in 2025-06, with the labels that each got.

#117 Proper Daily Summaries
  .gitignore
  API/PirateDailyText.py
  API/PirateMinutelyText.py
  API/PirateSimpleDaily.py
  API/PirateText.py
  API/PirateTextHelper.py
  API/PirateWeeklyText.py
Labels: enhancement, help wanted

#112 Handle all wgrib2 calls to exit if they fail
  API/GEFS_Local_Ingest.py
  API/GFS_Local_Ingest.py
  API/HRRR_6H_Local_Ingest.py
  API/HRRR_Local_Ingest.py
  API/NBM_Fire_Local_Ingest.py
  API/NBM_Local_Ingest.py
  API/SubH_Local_Ingest.py
Labels: enhancement, Needs Review

#140 Fix maxWind calculations
  API/PirateDailyText.py
Labels: bugfix

#165 Update dependencies
  Docker/requirements-api.txt
  requirements-lint.txt
Labels: dependencies, python

#167 Add S3 live forecast test
  .github/workflows/test.yml
  API/__init__.py
  tests/test_s3_live.py
Labels: codex

#169 Fix remaining summary issues?
  .github/workflows/dev-compare.yml
  API/PirateDailyText.py
  requirements-lint.txt
  tests/__init__.py
  tests/test_compare_production.py
  tests/test_s3_live.py
  tests/test_text_helper.py
Labels: bugfix

#173 Add AGENTS instructions
  AGENTS.md
Labels: codex

#174 Update VEnv docs
  README.md
Labels: documentation
