Repository Pirate-Weather/pirate-weather-code, pull requests merged in 2025-08, with the labels that each got.

#221 Update dependencies
  .github/workflows/test.yml
  Docker/requirements-api.txt
  Docker/requirements-ingest.txt
  requirements-lint.txt
Labels: dependencies

#230 Fix inconsistencies in visibility thresholds
  API/PirateTextHelper.py
Labels: bugfix

#231 Change dev version
  API/responseLocal.py
  API/timemachine.py
Labels: bugfix

#242 Change minutely `precipIntensity` to use reflectivity
  .github/workflows/test.yml
  API/GFS_Local_Ingest.py
  API/HRRR_6H_Local_Ingest.py
  API/HRRR_Local_Ingest.py
  API/SubH_Local_Ingest.py
  API/ingest_utils.py
  API/responseLocal.py
Labels: enhancement

#243 Change minutely `precipIntensity` to use reflectivity
  API/GFS_Local_Ingest.py
  API/HRRR_6H_Local_Ingest.py
  API/HRRR_Local_Ingest.py
  API/PirateTextHelper.py
  API/SubH_Local_Ingest.py
  API/ingest_utils.py
  API/responseLocal.py
Labels: enhancement
