Repository Pirate-Weather/pirate-weather-code, pull requests merged in 2025-03, with the labels that each got.

#84 Add CI and fix Docker build
  .github/workflows/sanity.yml
  Docker/pirate-ingest-dockerfile
  Docker/requirements-ingest.txt
Labels: enhancement, github_actions

#93 API Version 2.5.4
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/sanity.yml
  API/PirateText.py
  API/responseLocal.py
  API/timemachine.py
  Docker/pirate-api-dockerfile
  Docker/pirate-ingest-dockerfile
  Docker/requirements-api.txt
  Docker/requirements-ingest.txt
  requirements-lint.txt
Labels: enhancement, bugfix

#91 Add simple daily summaries
  API/PirateSimpleDaily.py
  API/responseLocal.py
Labels: enhancement, Needs Review
