Repository Pirate-Weather/pirate-weather-code, pull requests merged in 2025-04, with the labels that each got.

#66 API Version 2.6 Text Summaries
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  API/PirateDailyText.py
  API/PirateMinutelyText.py
  API/PirateSimpleDayText.py
  API/PirateText.py
  API/PirateTextHelper.py
  API/PirateWeeklyText.py
  API/responseLocal.py
  Docker/pirate-api-dockerfile
  Docker/requirements-api.txt
Labels: enhancement, Needs Review

#101 API V2.6 Summaries
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  API/PirateDailyText.py
  API/PirateMinutelyText.py
  API/PirateSimpleDayText.py
  API/PirateText.py
  API/PirateTextHelper.py
  API/PirateWeeklyText.py
  API/responseLocal.py
  Docker/pirate-api-dockerfile
  Docker/requirements-api.txt
Labels: enhancement

#92 Move to zarr.storage.LocalStore
  .github/workflows/build.yml
  .github/workflows/sanity.yml
  .gitignore
  API/ECMWF_Local_Ingest.py
  API/GEFS_Local_Ingest.py
  API/GFS_Dask_Ingest.py
  API/GFS_Local_Ingest.py
  API/HRRR_6H_Local_Ingest.py
  API/HRRR_Local_Ingest.py
  API/NBM_Fire_Local_Ingest.py
  API/NBM_Local_Ingest.py
  API/NWS_Alerts_Local.py
  API/SubH_Local_Ingest.py
  Docker/pirate-ingest-dockerfile
  Docker/requirements-ingest.txt
  pirate-compose_oph
Labels: enhancement, bugfix

#111 Updated day summaries
  API/PirateDailyText.py
  API/PirateMinutelyText.py
  API/PirateSimpleDayText.py
  API/responseLocal.py
Labels: enhancement, Needs Review
